// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbAW6PnqnFJAM7b8oFofSXKzdpOf2H_ww',
    appId: '1:852264246013:web:cc52b373e9c082a2ebfc94',
    messagingSenderId: '852264246013',
    projectId: 'ppl-iwan',
    authDomain: 'ppl-iwan.firebaseapp.com',
    storageBucket: 'ppl-iwan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlzGuG-3RUWR1RpNpJjWwip7Xnh4F-NM',
    appId: '1:852264246013:android:cfda2ebe5eaa7f45ebfc94',
    messagingSenderId: '852264246013',
    projectId: 'ppl-iwan',
    storageBucket: 'ppl-iwan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJjg4Xk_Ddiahg5v0jjxAO_DG-EZgmkg',
    appId: '1:852264246013:ios:c7b54e731c1a532febfc94',
    messagingSenderId: '852264246013',
    projectId: 'ppl-iwan',
    storageBucket: 'ppl-iwan.firebasestorage.app',
    iosBundleId: 'com.example.wormsupDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSJjg4Xk_Ddiahg5v0jjxAO_DG-EZgmkg',
    appId: '1:852264246013:ios:c7b54e731c1a532febfc94',
    messagingSenderId: '852264246013',
    projectId: 'ppl-iwan',
    storageBucket: 'ppl-iwan.firebasestorage.app',
    iosBundleId: 'com.example.wormsupDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbAW6PnqnFJAM7b8oFofSXKzdpOf2H_ww',
    appId: '1:852264246013:web:7b15a004730db1eeebfc94',
    messagingSenderId: '852264246013',
    projectId: 'ppl-iwan',
    authDomain: 'ppl-iwan.firebaseapp.com',
    storageBucket: 'ppl-iwan.firebasestorage.app',
  );
}
